name: Java CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: rijhwaniritesh24/action-test/.github/workflows/action.yaml@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}


